import { AnomalyCard, Intervention, RoutineTask, ReportItem, SAPOrderHeader } from './types';
import { simulationEngine } from './data/simulationEngine';
import { insightEngine, Insight } from './data/insightEngine';

// --- Connected Data (Generated by Simulation Engine) ---
export const mockSAPOrders: SAPOrderHeader[] = simulationEngine.getOrders();
export const mockInsights: Insight[] = insightEngine.analyzeOrders(mockSAPOrders);
export const mockAnomalies: AnomalyCard[] = simulationEngine.generateAnomalies(5);
export const mockInterventions: Intervention[] = simulationEngine.generateInterventions(8);

// --- Static / UI Specific Data (Still mocked for now as they are less critical for connectedness) ---

// Recharts data
export const mockChartData = [
    { name: 'א', value: 400, uv: 2400, pv: 2400, amt: 2400 },
    { name: 'ב', value: 300, uv: 1398, pv: 2210, amt: 2210 },
    { name: 'ג', value: 200, uv: 9800, pv: 2290, amt: 2290 },
    { name: 'ד', value: 278, uv: 3908, pv: 2000, amt: 2000 },
    { name: 'ה', value: 189, uv: 4800, pv: 2181, amt: 2181 },
    { name: 'ו', value: 239, uv: 3800, pv: 2500, amt: 2500 },
    { name: 'ש', value: 349, uv: 4300, pv: 2100, amt: 2100 },
];

export const mockBenchmarks = [
    { metric: 'זמינות מבצעית', unit: '%', myWorkshop: 92, avgWorkshop: 85, bestClass: 98 },
    { metric: 'משך טיפול ממוצע', unit: 'שעות', myWorkshop: 4.5, avgWorkshop: 6.2, bestClass: 3.8 },
    { metric: 'תקלות חוזרות', unit: '%', myWorkshop: 2.1, avgWorkshop: 5.5, bestClass: 0.5 },
    { metric: 'שביעות רצון (משוב)', unit: 'ציון', myWorkshop: 4.8, avgWorkshop: 4.2, bestClass: 4.9 }
];

export const mockRoutineTasks: RoutineTask[] = [
    { id: '1', title: 'בדיקת בוקר', status: 'completed', assignee: 'דני', dueDate: '08:00', time: '08:00' },
    { id: '2', title: 'טיפול שבועי', status: 'in-progress', assignee: 'יוסי', dueDate: '12:00', time: '12:00' }
];

export const mockReports: ReportItem[] = [
    { id: '1', title: 'דו״ח חודשי', dateCreated: '2026-05-01', status: 'מוכן', type: 'Monthly', size: '1.2MB' },
    { id: '2', title: 'חריגות מלאי', dateCreated: '2026-05-02', status: 'בבדיקה', type: 'Weekly', size: '840KB' }
];


export const mockAnomalyCauses = [
    { name: 'טעות אנוש', value: 400, color: '#f43f5e' },
    { name: 'תקלה טכנית', value: 300, color: '#3b82f6' },
    { name: 'דיווח חסר', value: 300, color: '#f59e0b' },
    { name: 'אחר', value: 200, color: '#64748b' }
];

export const mockNormCompliance = [
    { domain: 'מערכות ממונעות', totalOrders: 152, meetingNorm: 135, percentage: 89 },
    { domain: 'נשק ותחמושת', totalOrders: 98, meetingNorm: 98, percentage: 100 },
    { domain: 'אופטיקה', totalOrders: 45, meetingNorm: 30, percentage: 66 },
    { domain: 'תקשוב', totalOrders: 210, meetingNorm: 180, percentage: 85 }
];
